# Generated by Django 5.2.2 on 2026-02-11 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0004_profile_age_profile_name_profile_profile_picture"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="language",
            field=models.CharField(
                choices=[("en-us", "English"), ("hi", "Hindi")],
                default="en-us",
                max_length=10,
            ),
        ),
    ]
