# Generated by Django 5.2.2 on 2026-04-03 04:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_profile_language'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='user_type',
            field=models.CharField(choices=[('Farmer', 'Commercial Farmer'), ('Hobbyist', 'Hobbyist/Gardener')], default='Farmer', max_length=20),
        ),
    ]
