# Generated by Django 5.2.2 on 2026-02-11 13:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Crop",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
                ("scientific_name", models.CharField(max_length=100)),
                ("overview", models.TextField()),
                (
                    "header_image",
                    models.ImageField(blank=True, null=True, upload_to="crop_headers/"),
                ),
                (
                    "planting_method",
                    models.TextField(help_text="Detailed planting instructions"),
                ),
                (
                    "soil_water_req",
                    models.TextField(help_text="Soil type and water requirements"),
                ),
                (
                    "growth_fertilizers",
                    models.TextField(help_text="Fertilizer schedule and growth care"),
                ),
                ("sowing_season", models.CharField(max_length=100)),
                ("harvesting_season", models.CharField(max_length=100)),
                (
                    "growth_duration",
                    models.CharField(help_text="e.g. 120-150 days", max_length=100),
                ),
                (
                    "average_price",
                    models.CharField(
                        help_text="e.g. ₹2000 - ₹2500 / quintal", max_length=100
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Disease",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("symptoms", models.TextField()),
                (
                    "medicine_protection",
                    models.TextField(help_text="Preventative measures"),
                ),
                ("medicine_cure", models.TextField(help_text="Curative medicines")),
                (
                    "image",
                    models.ImageField(
                        blank=True, null=True, upload_to="disease_images/"
                    ),
                ),
                (
                    "crop",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="diseases",
                        to="dictionary.crop",
                    ),
                ),
            ],
        ),
    ]
