# Generated by Django 5.2.2 on 2026-02-11 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dictionary", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="crop",
            name="growth_fertilizers",
        ),
        migrations.RemoveField(
            model_name="crop",
            name="planting_method",
        ),
        migrations.RemoveField(
            model_name="crop",
            name="soil_water_req",
        ),
        migrations.AddField(
            model_name="crop",
            name="climatic_req",
            field=models.TextField(blank=True, help_text="Temp, Humidity, Rainfall"),
        ),
        migrations.AddField(
            model_name="crop",
            name="crop_rotation",
            field=models.TextField(
                blank=True, help_text="Preceding and succeeding crops"
            ),
        ),
        migrations.AddField(
            model_name="crop",
            name="family",
            field=models.CharField(
                blank=True, help_text="e.g., Solanaceae", max_length=100
            ),
        ),
        migrations.AddField(
            model_name="crop",
            name="fertilizer_schedule",
            field=models.TextField(
                blank=True, help_text="NPK requirements and schedule"
            ),
        ),
        migrations.AddField(
            model_name="crop",
            name="growth_habit",
            field=models.CharField(
                blank=True,
                help_text="e.g., Annual shrub, Perennial tree",
                max_length=100,
            ),
        ),
        migrations.AddField(
            model_name="crop",
            name="harvesting_method",
            field=models.TextField(
                blank=True, help_text="Manual or mechanical details"
            ),
        ),
        migrations.AddField(
            model_name="crop",
            name="ipm_practices",
            field=models.TextField(
                blank=True, help_text="Integrated Pest Management strategies"
            ),
        ),
        migrations.AddField(
            model_name="crop",
            name="major_pests",
            field=models.TextField(blank=True, help_text="List of major insect pests"),
        ),
        migrations.AddField(
            model_name="crop",
            name="maturity_signs",
            field=models.TextField(
                blank=True, help_text="Physical indicators of maturity"
            ),
        ),
        migrations.AddField(
            model_name="crop",
            name="micronutrients",
            field=models.TextField(
                blank=True, help_text="Deficiency signs and management"
            ),
        ),
        migrations.AddField(
            model_name="crop",
            name="pollination",
            field=models.CharField(
                blank=True,
                help_text="e.g., Self-pollinated, Cross-pollinated",
                max_length=100,
            ),
        ),
        migrations.AddField(
            model_name="crop",
            name="processing_value",
            field=models.TextField(blank=True, help_text="Value-added products"),
        ),
        migrations.AddField(
            model_name="crop",
            name="seed_rate_spacing",
            field=models.TextField(blank=True, help_text="Seeds per acre and spacing"),
        ),
        migrations.AddField(
            model_name="crop",
            name="soil_ph",
            field=models.CharField(
                blank=True, help_text="e.g., 6.0 - 7.0", max_length=50
            ),
        ),
        migrations.AddField(
            model_name="crop",
            name="soil_type",
            field=models.CharField(
                blank=True, help_text="e.g., Well-drained loamy soil", max_length=100
            ),
        ),
        migrations.AddField(
            model_name="crop",
            name="sowing_window",
            field=models.CharField(
                blank=True,
                help_text="Specific seasons (Kharif/Rabi) and months",
                max_length=100,
            ),
        ),
        migrations.AddField(
            model_name="crop",
            name="storage_req",
            field=models.TextField(
                blank=True, help_text="Temp, humidity, and shelf-life"
            ),
        ),
        migrations.AddField(
            model_name="crop",
            name="varieties",
            field=models.TextField(
                blank=True, help_text="Popular local and global breeds"
            ),
        ),
        migrations.AddField(
            model_name="crop",
            name="water_req",
            field=models.TextField(
                blank=True, help_text="Irrigation frequency and critical stages"
            ),
        ),
        migrations.AddField(
            model_name="crop",
            name="weed_control",
            field=models.TextField(
                blank=True, help_text="Herbicides and manual weeding"
            ),
        ),
        migrations.AddField(
            model_name="crop",
            name="wikipedia_url",
            field=models.URLField(
                blank=True, help_text="Link to Wikipedia article", null=True
            ),
        ),
        migrations.AddField(
            model_name="crop",
            name="yield_expectations",
            field=models.CharField(
                blank=True, help_text="e.g., 20-25 tonnes/ha", max_length=100
            ),
        ),
        migrations.AlterField(
            model_name="crop",
            name="average_price",
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name="crop",
            name="growth_duration",
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name="crop",
            name="sowing_season",
            field=models.CharField(
                help_text="Short season name (e.g. Kharif)", max_length=100
            ),
        ),
    ]
