# Generated by Django 5.2.2 on 2026-02-16 09:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('dictionary', '0002_remove_crop_growth_fertilizers_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CropTracker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('crop_name_custom', models.CharField(blank=True, help_text='Use this if the crop is not in the dictionary', max_length=100, null=True)),
                ('quantity', models.FloatField(help_text='Number of crops or acres')),
                ('unit', models.CharField(default='Acres', help_text='Unit of measurement (e.g., Acres, Plants)', max_length=50)),
                ('planting_date', models.DateField()),
                ('harvest_date', models.DateField(blank=True, null=True)),
                ('growth_phase', models.CharField(choices=[('Sowing', 'Sowing'), ('Germination', 'Germination'), ('Vegetative', 'Vegetative'), ('Flowering', 'Flowering'), ('Fruiting', 'Fruiting'), ('Maturation', 'Maturation'), ('Harvested', 'Harvested')], default='Sowing', max_length=50)),
                ('cost', models.DecimalField(decimal_places=2, default=0.0, help_text='Total money spent on this crop', max_digits=10)),
                ('revenue', models.DecimalField(decimal_places=2, default=0.0, help_text='Total money earned from sales', max_digits=10)),
                ('strategy', models.TextField(blank=True, help_text='Your notes or strategies for this crop')),
                ('status', models.CharField(choices=[('Active', 'Active'), ('Completed', 'Completed')], default='Active', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('crop', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tracked_instances', to='dictionary.crop')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tracked_crops', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
