# Generated by Django 5.2.2 on 2026-02-16 16:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dictionary', '0002_remove_crop_growth_fertilizers_and_more'),
        ('tracker', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='croptracker',
            options={'ordering': ['-planting_date']},
        ),
        migrations.AlterField(
            model_name='croptracker',
            name='cost',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='croptracker',
            name='crop',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='dictionary.crop'),
        ),
        migrations.AlterField(
            model_name='croptracker',
            name='crop_name_custom',
            field=models.CharField(blank=True, default='', help_text='Custom crop name if not in dictionary', max_length=100),
        ),
        migrations.AlterField(
            model_name='croptracker',
            name='growth_phase',
            field=models.CharField(choices=[('Sowing', 'Sowing'), ('Germination', 'Germination'), ('Vegetative', 'Vegetative'), ('Flowering', 'Flowering'), ('Fruiting', 'Fruiting'), ('Maturation', 'Maturation')], default='Sowing', max_length=50),
        ),
        migrations.AlterField(
            model_name='croptracker',
            name='quantity',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='croptracker',
            name='revenue',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='croptracker',
            name='strategy',
            field=models.TextField(blank=True, help_text='Notes or strategy for this crop'),
        ),
        migrations.AlterField(
            model_name='croptracker',
            name='unit',
            field=models.CharField(default='kg', max_length=50),
        ),
    ]
