# Generated by Django 5.2.2 on 2026-02-17 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0002_alter_croptracker_options_alter_croptracker_cost_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='croptracker',
            name='location',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
