# Generated by Django 5.2.2 on 2026-04-03 05:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0003_croptracker_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='croptracker',
            name='field_area_acres',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='croptracker',
            name='field_polygon',
            field=models.TextField(blank=True, help_text='GeoJSON or coordinate string for the field map'),
        ),
        migrations.CreateModel(
            name='FinancialEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entry_type', models.CharField(choices=[('Expense', 'Expense'), ('Revenue', 'Revenue')], max_length=20)),
                ('category', models.CharField(choices=[('Seed', 'Seed'), ('Fertilizer', 'Fertilizer'), ('Pesticide', 'Pesticide'), ('Labor', 'Labor'), ('Equipment', 'Equipment'), ('Harvest/Sale', 'Harvest/Sale'), ('Other', 'Other')], max_length=50)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('date', models.DateField(auto_now_add=True)),
                ('description', models.CharField(blank=True, max_length=255)),
                ('crop_tracker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='financials', to='tracker.croptracker')),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('due_date', models.DateField()),
                ('is_completed', models.BooleanField(default=False)),
                ('crop_tracker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='tracker.croptracker')),
            ],
            options={
                'ordering': ['due_date'],
            },
        ),
    ]
