# Generated by Django 5.2.2 on 2026-04-04 20:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0004_croptracker_field_area_acres_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='croptracker',
            name='emoji',
            field=models.CharField(default='🌿', help_text='Emoji for visual identification', max_length=10),
        ),
        migrations.AddField(
            model_name='croptracker',
            name='health',
            field=models.CharField(choices=[('Healthy', 'Healthy'), ('Attention', 'Attention'), ('At Risk', 'At Risk')], default='Healthy', max_length=20),
        ),
        migrations.CreateModel(
            name='ActivityLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity_type', models.CharField(max_length=50)),
                ('details', models.CharField(blank=True, max_length=255)),
                ('date', models.DateField(auto_now_add=True)),
                ('crop_tracker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='tracker.croptracker')),
            ],
            options={
                'ordering': ['-date', '-id'],
            },
        ),
    ]
