# Generated by Django 5.2.2 on 2026-04-05 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0005_croptracker_emoji_croptracker_health_activitylog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activitylog',
            name='date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
