# Generated by Django 5.2.2 on 2026-04-13 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0006_activitylog_date_to_datetimefield'),
    ]

    operations = [
        migrations.AddField(
            model_name='croptracker',
            name='phase_updated_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
